version: "3.2"
services:
  primary:
    image: postgres:15.1
    container_name: primary
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data-primary:/var/lib/postgresql/data
      - ./init-primary.sql:/docker-entrypoint-initdb.d/setup.sql
    expose:
      - 5432
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  replica1:
    image: postgres:15.1
    container_name: replica1
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data-replica1:/var/lib/postgresql/data
      - ./init-replica1.sql:/docker-entrypoint-initdb.d/setup.sql
    expose:
      - 5432
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  replica2:
    image: postgres:15.1
    container_name: replica2
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data-replica2:/var/lib/postgresql/data
      - ./init-replica2.sql:/docker-entrypoint-initdb.d/setup.sql
    expose:
      - 5432
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data-primary:
  postgres-data-replica1:
  postgres-data-replica2:
